version: '3.8'

services:
  app:
    image: 'savingstrackerapi:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    ports:
      - '8080:8080'

  db:
    image: 'postgres:13.1-alpine'
    container_name: db_savings_tracker
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=remo1921
      - POSTGRES_PASSWORD=Remo1921
      - POSTGRES_DB=savings_tracker

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: admin12345678